enableGlobalCache: true
globalFolder: .yarn/global
nodeLinker: pnp
plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
pnpMode: strict
pnpUnpluggedFolder: .yarn/unplugged
